// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  mode: __t.string(),
  phase: __t.string(),
  revision: __t.u64(),
  leftIdentity: __t.option(__t.identity()).name("left_identity"),
  rightIdentity: __t.option(__t.identity()).name("right_identity"),
  leftName: __t.string().name("left_name"),
  rightName: __t.string().name("right_name"),
  leftIntent: __t.string().name("left_intent"),
  rightIntent: __t.string().name("right_intent"),
  deadlineMicros: __t.u64().name("deadline_micros"),
  notice: __t.string(),
});
