// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  revision: __t.u32(),
  state: __t.string(),
  phase: __t.string(),
  mode: __t.string(),
  leftPolicy: __t.string().name("left_policy"),
  rightPolicy: __t.string().name("right_policy"),
  agentIdentity: __t.option(__t.identity()).name("agent_identity"),
  provenance: __t.string(),
});
