// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  sourceMatchId: __t.u64().name("source_match_id"),
  sourceFrameId: __t.u64().name("source_frame_id"),
  startRevision: __t.u32().name("start_revision"),
  rulesVersion: __t.u32().name("rules_version"),
  opponentPolicy: __t.string().name("opponent_policy"),
  createdAt: __t.timestamp().name("created_at"),
});
