// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  innings: __t.u32(),
  turn: __t.string(),
  humanScore: __t.u32().name("human_score"),
  botScore: __t.u32().name("bot_score"),
  humanBalls: __t.u32().name("human_balls"),
  botBalls: __t.u32().name("bot_balls"),
  humanWickets: __t.u32().name("human_wickets"),
  botWickets: __t.u32().name("bot_wickets"),
  target: __t.u32(),
  lastOutcome: __t.string().name("last_outcome"),
  humanTimeline: __t.string().name("human_timeline"),
  botTimeline: __t.string().name("bot_timeline"),
  lastCrowdSwing: __t.string().name("last_crowd_swing"),
  seed: __t.u64(),
});
