// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  edges: __t.string(),
  boxes: __t.string(),
  humanBoxes: __t.u32().name("human_boxes"),
  botBoxes: __t.u32().name("bot_boxes"),
  turn: __t.string(),
  revision: __t.u32(),
  lastOutcome: __t.string().name("last_outcome"),
  seed: __t.u64(),
});
