// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AgentFlickReducer from "./agent_flick_reducer";
import BeginProfileLinkReducer from "./begin_profile_link_reducer";
import ClaimAgentSeatReducer from "./claim_agent_seat_reducer";
import CompleteProfileLinkReducer from "./complete_profile_link_reducer";
import CreateAgentDuelReducer from "./create_agent_duel_reducer";
import CreateBookCricketReducer from "./create_book_cricket_reducer";
import CreateDotsBoxesReducer from "./create_dots_boxes_reducer";
import CreateGilliDandaReducer from "./create_gilli_danda_reducer";
import CreatePenFightReducer from "./create_pen_fight_reducer";
import DrawDotsEdgeReducer from "./draw_dots_edge_reducer";
import FlickPenReducer from "./flick_pen_reducer";
import JoinMatchAsSpectatorReducer from "./join_match_as_spectator_reducer";
import LiftGilliReducer from "./lift_gilli_reducer";
import OnboardReducer from "./onboard_reducer";
import OnboardWithEmailReducer from "./onboard_with_email_reducer";
import PlayBallReducer from "./play_ball_reducer";
import StrikeGilliReducer from "./strike_gilli_reducer";
import UseCrowdPowerReducer from "./use_crowd_power_reducer";
import UseExperimentalCrowdPowerReducer from "./use_experimental_crowd_power_reducer";
import UsePenFightCrowdPowerReducer from "./use_pen_fight_crowd_power_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentDuelRow from "./agent_duel_table";
import AiCharacterRow from "./ai_character_table";
import BookCricketRecordRow from "./book_cricket_record_table";
import BookCricketStateRow from "./book_cricket_state_table";
import DotsBoxesStateRow from "./dots_boxes_state_table";
import DuelCrowdCreditRow from "./duel_crowd_credit_table";
import GilliDandaStateRow from "./gilli_danda_state_table";
import GilliLaunchRow from "./gilli_launch_table";
import LiveEventRow from "./live_event_table";
import MatchRow from "./match_table";
import MatchCrowdRow from "./match_crowd_table";
import MatchHistoryRow from "./match_history_table";
import MatchMemoryRow from "./match_memory_table";
import MatchParticipantRow from "./match_participant_table";
import MatchSpectatorRow from "./match_spectator_table";
import MelaMetricsRow from "./mela_metrics_table";
import MelaProfileRow from "./mela_profile_table";
import MyEmailContactRow from "./my_email_contact_table";
import MyIdentityLinkRow from "./my_identity_link_table";
import OwnSpectatorCooldownRow from "./own_spectator_cooldown_table";
import PenDeskStateRow from "./pen_desk_state_table";
import PenFightMetricsRow from "./pen_fight_metrics_table";
import PenFightRecordRow from "./pen_fight_record_table";
import PlayerProfileRow from "./player_profile_table";
import VisibleCrowdEffectsRow from "./visible_crowd_effects_table";
import WorldRow from "./world_table";
import WorldActivityRow from "./world_activity_table";
import WorldPresenceRow from "./world_presence_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agentDuel: __table(
    {
      name: "agent_duel",
      indexes: [
        {
          accessor: "matchId",
          name: "agent_duel_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "agent_duel_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    AgentDuelRow,
  ),
  aiCharacter: __table(
    {
      name: "ai_character",
      indexes: [
        {
          accessor: "id",
          name: "ai_character_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "ai_character_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    AiCharacterRow,
  ),
  bookCricketRecord: __table(
    {
      name: "book_cricket_record",
      indexes: [
        {
          accessor: "identity",
          name: "book_cricket_record_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
      ],
      constraints: [
        {
          name: "book_cricket_record_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    BookCricketRecordRow,
  ),
  bookCricketState: __table(
    {
      name: "book_cricket_state",
      indexes: [
        {
          accessor: "matchId",
          name: "book_cricket_state_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "book_cricket_state_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    BookCricketStateRow,
  ),
  dotsBoxesState: __table(
    {
      name: "dots_boxes_state",
      indexes: [
        {
          accessor: "matchId",
          name: "dots_boxes_state_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "dots_boxes_state_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    DotsBoxesStateRow,
  ),
  duelCrowdCredit: __table(
    {
      name: "duel_crowd_credit",
      indexes: [
        {
          accessor: "id",
          name: "duel_crowd_credit_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        {
          name: "duel_crowd_credit_id_key",
          constraint: "unique",
          columns: ["id"],
        },
      ],
    },
    DuelCrowdCreditRow,
  ),
  gilliDandaState: __table(
    {
      name: "gilli_danda_state",
      indexes: [
        {
          accessor: "matchId",
          name: "gilli_danda_state_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "gilli_danda_state_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    GilliDandaStateRow,
  ),
  gilliLaunch: __table(
    {
      name: "gilli_launch",
      indexes: [
        {
          accessor: "matchId",
          name: "gilli_launch_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "gilli_launch_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    GilliLaunchRow,
  ),
  liveEvent: __table(
    {
      name: "live_event",
      indexes: [
        {
          accessor: "id",
          name: "live_event_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "live_event_id_key", constraint: "unique", columns: ["id"] },
      ],
      event: true,
    },
    LiveEventRow,
  ),
  match: __table(
    {
      name: "match",
      indexes: [
        {
          accessor: "id",
          name: "match_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "match_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    MatchRow,
  ),
  matchCrowd: __table(
    {
      name: "match_crowd",
      indexes: [
        {
          accessor: "matchId",
          name: "match_crowd_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "match_crowd_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    MatchCrowdRow,
  ),
  matchHistory: __table(
    {
      name: "match_history",
      indexes: [
        {
          accessor: "id",
          name: "match_history_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "match_history_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    MatchHistoryRow,
  ),
  matchMemory: __table(
    {
      name: "match_memory",
      indexes: [
        {
          accessor: "matchId",
          name: "match_memory_match_id_idx_btree",
          algorithm: "btree",
          columns: ["matchId"],
        },
      ],
      constraints: [
        {
          name: "match_memory_match_id_key",
          constraint: "unique",
          columns: ["matchId"],
        },
      ],
    },
    MatchMemoryRow,
  ),
  matchParticipant: __table(
    {
      name: "match_participant",
      indexes: [
        {
          accessor: "id",
          name: "match_participant_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        {
          name: "match_participant_id_key",
          constraint: "unique",
          columns: ["id"],
        },
      ],
    },
    MatchParticipantRow,
  ),
  matchSpectator: __table(
    {
      name: "match_spectator",
      indexes: [
        {
          accessor: "id",
          name: "match_spectator_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        {
          name: "match_spectator_id_key",
          constraint: "unique",
          columns: ["id"],
        },
      ],
    },
    MatchSpectatorRow,
  ),
  melaMetrics: __table(
    {
      name: "mela_metrics",
      indexes: [
        {
          accessor: "id",
          name: "mela_metrics_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "mela_metrics_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    MelaMetricsRow,
  ),
  melaProfile: __table(
    {
      name: "mela_profile",
      indexes: [
        {
          accessor: "identity",
          name: "mela_profile_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
      ],
      constraints: [
        {
          name: "mela_profile_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    MelaProfileRow,
  ),
  penFightMetrics: __table(
    {
      name: "pen_fight_metrics",
      indexes: [
        {
          accessor: "id",
          name: "pen_fight_metrics_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        {
          name: "pen_fight_metrics_id_key",
          constraint: "unique",
          columns: ["id"],
        },
      ],
    },
    PenFightMetricsRow,
  ),
  penFightRecord: __table(
    {
      name: "pen_fight_record",
      indexes: [
        {
          accessor: "identity",
          name: "pen_fight_record_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
      ],
      constraints: [
        {
          name: "pen_fight_record_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    PenFightRecordRow,
  ),
  playerProfile: __table(
    {
      name: "player_profile",
      indexes: [
        {
          accessor: "identity",
          name: "player_profile_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
      ],
      constraints: [
        {
          name: "player_profile_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    PlayerProfileRow,
  ),
  world: __table(
    {
      name: "world",
      indexes: [
        {
          accessor: "id",
          name: "world_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        { name: "world_id_key", constraint: "unique", columns: ["id"] },
      ],
    },
    WorldRow,
  ),
  worldActivity: __table(
    {
      name: "world_activity",
      indexes: [
        {
          accessor: "id",
          name: "world_activity_id_idx_btree",
          algorithm: "btree",
          columns: ["id"],
        },
      ],
      constraints: [
        {
          name: "world_activity_id_key",
          constraint: "unique",
          columns: ["id"],
        },
      ],
    },
    WorldActivityRow,
  ),
  worldPresence: __table(
    {
      name: "world_presence",
      indexes: [
        {
          accessor: "identity",
          name: "world_presence_identity_idx_btree",
          algorithm: "btree",
          columns: ["identity"],
        },
      ],
      constraints: [
        {
          name: "world_presence_identity_key",
          constraint: "unique",
          columns: ["identity"],
        },
      ],
    },
    WorldPresenceRow,
  ),
  myEmailContact: __table(
    {
      name: "my_email_contact",
      indexes: [],
      constraints: [],
    },
    MyEmailContactRow,
  ),
  myIdentityLink: __table(
    {
      name: "my_identity_link",
      indexes: [],
      constraints: [],
    },
    MyIdentityLinkRow,
  ),
  ownSpectatorCooldown: __table(
    {
      name: "own_spectator_cooldown",
      indexes: [],
      constraints: [],
    },
    OwnSpectatorCooldownRow,
  ),
  penDeskState: __table(
    {
      name: "pen_desk_state",
      indexes: [],
      constraints: [],
    },
    PenDeskStateRow,
  ),
  visibleCrowdEffects: __table(
    {
      name: "visible_crowd_effects",
      indexes: [],
      constraints: [],
    },
    VisibleCrowdEffectsRow,
  ),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("agent_flick", AgentFlickReducer),
  __reducerSchema("begin_profile_link", BeginProfileLinkReducer),
  __reducerSchema("claim_agent_seat", ClaimAgentSeatReducer),
  __reducerSchema("complete_profile_link", CompleteProfileLinkReducer),
  __reducerSchema("create_agent_duel", CreateAgentDuelReducer),
  __reducerSchema("create_book_cricket", CreateBookCricketReducer),
  __reducerSchema("create_dots_boxes", CreateDotsBoxesReducer),
  __reducerSchema("create_gilli_danda", CreateGilliDandaReducer),
  __reducerSchema("create_pen_fight", CreatePenFightReducer),
  __reducerSchema("draw_dots_edge", DrawDotsEdgeReducer),
  __reducerSchema("flick_pen", FlickPenReducer),
  __reducerSchema("join_match_as_spectator", JoinMatchAsSpectatorReducer),
  __reducerSchema("lift_gilli", LiftGilliReducer),
  __reducerSchema("onboard", OnboardReducer),
  __reducerSchema("onboard_with_email", OnboardWithEmailReducer),
  __reducerSchema("play_ball", PlayBallReducer),
  __reducerSchema("strike_gilli", StrikeGilliReducer),
  __reducerSchema("use_crowd_power", UseCrowdPowerReducer),
  __reducerSchema(
    "use_experimental_crowd_power",
    UseExperimentalCrowdPowerReducer,
  ),
  __reducerSchema("use_pen_fight_crowd_power", UsePenFightCrowdPowerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures();

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> =
  __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(
  reducersSchema.reducersType.reducers,
);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<
  typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<
  typeof REMOTE_MODULE
>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
  typeof REMOTE_MODULE
> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(
      REMOTE_MODULE,
      (config: __DbConnectionConfig<typeof REMOTE_MODULE>) =>
        new DbConnection(config),
    );
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
