// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  sequence: __t.u64(),
  gameKind: __t.string().name("game_kind"),
  humanName: __t.string().name("human_name"),
  aiName: __t.string().name("ai_name"),
  winner: __t.string(),
  humanScore: __t.u32().name("human_score"),
  humanWickets: __t.u32().name("human_wickets"),
  botScore: __t.u32().name("bot_score"),
  botWickets: __t.u32().name("bot_wickets"),
  crowdParticipants: __t.u32().name("crowd_participants"),
  crowdActions: __t.u32().name("crowd_actions"),
  crowdEnergySpent: __t.u32().name("crowd_energy_spent"),
  notableMoment: __t.string().name("notable_moment"),
  completedAt: __t.timestamp().name("completed_at"),
});
