// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  worldId: __t.u64().name("world_id"),
  gameKind: __t.string().name("game_kind"),
  playerIdentity: __t.identity().name("player_identity"),
  status: __t.string(),
  winner: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
