// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  melaLevel: __t.u32().name("mela_level"),
  progressPoints: __t.u32().name("progress_points"),
  matchesPlayed: __t.u32().name("matches_played"),
  matchesWon: __t.u32().name("matches_won"),
  matchesWatched: __t.u32().name("matches_watched"),
  crowdActions: __t.u32().name("crowd_actions"),
  crowdInfluence: __t.u32().name("crowd_influence"),
  updatedAt: __t.timestamp().name("updated_at"),
});
