// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchesStarted: __t.u64().name("matches_started"),
  matchesCompleted: __t.u64().name("matches_completed"),
  uniquePlayerIdentities: __t.u64().name("unique_player_identities"),
  uniqueSpectatorIdentities: __t.u64().name("unique_spectator_identities"),
  totalParticipants: __t.u64().name("total_participants"),
  crowdActions: __t.u64().name("crowd_actions"),
  completedPlayerMatches: __t.u64().name("completed_player_matches"),
  replayedMatches: __t.u64().name("replayed_matches"),
  spectatorToPlayerConversions: __t
    .u64()
    .name("spectator_to_player_conversions"),
  updatedAt: __t.timestamp().name("updated_at"),
});
