// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  round: __t.u32(),
  humanRounds: __t.u32().name("human_rounds"),
  botRounds: __t.u32().name("bot_rounds"),
  turn: __t.string(),
  humanX: __t.u32().name("human_x"),
  humanY: __t.u32().name("human_y"),
  botX: __t.u32().name("bot_x"),
  botY: __t.u32().name("bot_y"),
  turnsInRound: __t.u32().name("turns_in_round"),
  lastOutcome: __t.string().name("last_outcome"),
});
