// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  matchesStarted: __t.u64().name("matches_started"),
  matchesCompleted: __t.u64().name("matches_completed"),
  uniquePlayers: __t.u64().name("unique_players"),
  uniqueSpectators: __t.u64().name("unique_spectators"),
  participants: __t.u64(),
  crowdActions: __t.u64().name("crowd_actions"),
  roundsCompleted: __t.u64().name("rounds_completed"),
  knockouts: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
