// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentDuel = __t.object("AgentDuel", {
  matchId: __t.u64(),
  mode: __t.string(),
  phase: __t.string(),
  revision: __t.u64(),
  leftIdentity: __t.option(__t.identity()),
  rightIdentity: __t.option(__t.identity()),
  leftName: __t.string(),
  rightName: __t.string(),
  leftIntent: __t.string(),
  rightIntent: __t.string(),
  deadlineMicros: __t.u64(),
  notice: __t.string(),
});
export type AgentDuel = __Infer<typeof AgentDuel>;

export const AgentProposal = __t.object("AgentProposal", {
  matchId: __t.u64(),
  revision: __t.u64(),
  side: __t.string(),
  aimX: __t.u32(),
  aimY: __t.u32(),
  force: __t.u32(),
  contact: __t.u32(),
});
export type AgentProposal = __Infer<typeof AgentProposal>;

export const AiCharacter = __t.object("AiCharacter", {
  id: __t.u64(),
  characterKey: __t.string(),
  displayName: __t.string(),
  persona: __t.string(),
});
export type AiCharacter = __Infer<typeof AiCharacter>;

export const BookCricketRecord = __t.object("BookCricketRecord", {
  identity: __t.identity(),
  displayName: __t.string(),
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
  runsScored: __t.u32(),
  highestScore: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type BookCricketRecord = __Infer<typeof BookCricketRecord>;

export const BookCricketState = __t.object("BookCricketState", {
  matchId: __t.u64(),
  innings: __t.u32(),
  turn: __t.string(),
  humanScore: __t.u32(),
  botScore: __t.u32(),
  humanBalls: __t.u32(),
  botBalls: __t.u32(),
  humanWickets: __t.u32(),
  botWickets: __t.u32(),
  target: __t.u32(),
  lastOutcome: __t.string(),
  humanTimeline: __t.string(),
  botTimeline: __t.string(),
  lastCrowdSwing: __t.string(),
  lastPage: __t.u32(),
  seed: __t.u64(),
});
export type BookCricketState = __Infer<typeof BookCricketState>;

export const ConnectionSession = __t.object("ConnectionSession", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type ConnectionSession = __Infer<typeof ConnectionSession>;

export const CrowdEffect = __t.object("CrowdEffect", {
  id: __t.u64(),
  matchId: __t.u64(),
  power: __t.string(),
  target: __t.string(),
  actorName: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type CrowdEffect = __Infer<typeof CrowdEffect>;

export const CrowdSchedule = __t.object("CrowdSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  kind: __t.string(),
  matchId: __t.u64(),
  effectId: __t.u64(),
});
export type CrowdSchedule = __Infer<typeof CrowdSchedule>;

export const DotsBoxesState = __t.object("DotsBoxesState", {
  matchId: __t.u64(),
  edges: __t.string(),
  boxes: __t.string(),
  humanBoxes: __t.u32(),
  botBoxes: __t.u32(),
  turn: __t.string(),
  revision: __t.u32(),
  lastOutcome: __t.string(),
  seed: __t.u64(),
});
export type DotsBoxesState = __Infer<typeof DotsBoxesState>;

export const DuelCrowdCredit = __t.object("DuelCrowdCredit", {
  id: __t.u64(),
  matchId: __t.u64(),
  name: __t.string(),
  power: __t.string(),
});
export type DuelCrowdCredit = __Infer<typeof DuelCrowdCredit>;

export const EmailContact = __t.object("EmailContact", {
  identity: __t.identity(),
  email: __t.string(),
  source: __t.string(),
  verified: __t.bool(),
  createdAt: __t.timestamp(),
});
export type EmailContact = __Infer<typeof EmailContact>;

export const EmailMigration = __t.object("EmailMigration", {
  id: __t.u32(),
});
export type EmailMigration = __Infer<typeof EmailMigration>;

export const GilliDandaState = __t.object("GilliDandaState", {
  matchId: __t.u64(),
  round: __t.u32(),
  humanScore: __t.u32(),
  botScore: __t.u32(),
  turn: __t.string(),
  lastDistance: __t.u32(),
  lastSound: __t.string(),
  lastOutcome: __t.string(),
  seed: __t.u64(),
});
export type GilliDandaState = __Infer<typeof GilliDandaState>;

export const IdentityLink = __t.object("IdentityLink", {
  identity: __t.identity(),
  canonicalIdentity: __t.identity(),
  linkedAt: __t.timestamp(),
});
export type IdentityLink = __Infer<typeof IdentityLink>;

export const LiveEvent = __t.object("LiveEvent", {
  id: __t.u64(),
  matchId: __t.u64(),
  message: __t.string(),
  occurredAt: __t.timestamp(),
});
export type LiveEvent = __Infer<typeof LiveEvent>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  worldId: __t.u64(),
  gameKind: __t.string(),
  playerIdentity: __t.identity(),
  status: __t.string(),
  winner: __t.string(),
  createdAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
});
export type Match = __Infer<typeof Match>;

export const MatchCrowd = __t.object("MatchCrowd", {
  matchId: __t.u64(),
  energy: __t.u32(),
  maxEnergy: __t.u32(),
});
export type MatchCrowd = __Infer<typeof MatchCrowd>;

export const MatchCrowdActivity = __t.object("MatchCrowdActivity", {
  matchId: __t.u64(),
  actions: __t.u32(),
  energySpent: __t.u32(),
  lastActor: __t.string(),
  lastPower: __t.string(),
});
export type MatchCrowdActivity = __Infer<typeof MatchCrowdActivity>;

export const MatchHistory = __t.object("MatchHistory", {
  id: __t.u64(),
  matchId: __t.u64(),
  winner: __t.string(),
  humanScore: __t.u32(),
  botScore: __t.u32(),
  occurredAt: __t.timestamp(),
});
export type MatchHistory = __Infer<typeof MatchHistory>;

export const MatchMemory = __t.object("MatchMemory", {
  matchId: __t.u64(),
  sequence: __t.u64(),
  gameKind: __t.string(),
  humanName: __t.string(),
  aiName: __t.string(),
  winner: __t.string(),
  humanScore: __t.u32(),
  humanWickets: __t.u32(),
  botScore: __t.u32(),
  botWickets: __t.u32(),
  crowdParticipants: __t.u32(),
  crowdActions: __t.u32(),
  crowdEnergySpent: __t.u32(),
  notableMoment: __t.string(),
  completedAt: __t.timestamp(),
});
export type MatchMemory = __Infer<typeof MatchMemory>;

export const MatchParticipant = __t.object("MatchParticipant", {
  id: __t.u64(),
  matchId: __t.u64(),
  actorKind: __t.string(),
  role: __t.string(),
  identity: __t.option(__t.identity()),
  displayName: __t.string(),
});
export type MatchParticipant = __Infer<typeof MatchParticipant>;

export const MatchSpectator = __t.object("MatchSpectator", {
  id: __t.u64(),
  matchId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
});
export type MatchSpectator = __Infer<typeof MatchSpectator>;

export const MelaMetrics = __t.object("MelaMetrics", {
  id: __t.u64(),
  matchesStarted: __t.u64(),
  matchesCompleted: __t.u64(),
  uniquePlayerIdentities: __t.u64(),
  uniqueSpectatorIdentities: __t.u64(),
  totalParticipants: __t.u64(),
  crowdActions: __t.u64(),
  completedPlayerMatches: __t.u64(),
  replayedMatches: __t.u64(),
  spectatorToPlayerConversions: __t.u64(),
  abandonedMatches: __t.u64(),
  spectatorsWhoActed: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type MelaMetrics = __Infer<typeof MelaMetrics>;

export const MelaProfile = __t.object("MelaProfile", {
  identity: __t.identity(),
  melaLevel: __t.u32(),
  progressPoints: __t.u32(),
  matchesPlayed: __t.u32(),
  matchesWon: __t.u32(),
  matchesWatched: __t.u32(),
  crowdActions: __t.u32(),
  crowdInfluence: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MelaProfile = __Infer<typeof MelaProfile>;

export const MetricsIdentity = __t.object("MetricsIdentity", {
  identity: __t.identity(),
  hasPlayed: __t.u32(),
  hasSpectated: __t.u32(),
  completedPlayerMatches: __t.u32(),
  hasActed: __t.u32(),
});
export type MetricsIdentity = __Infer<typeof MetricsIdentity>;

export const MyEmailContact = __t.object("MyEmailContact", {});
export type MyEmailContact = __Infer<typeof MyEmailContact>;

export const MyIdentityLink = __t.object("MyIdentityLink", {});
export type MyIdentityLink = __Infer<typeof MyIdentityLink>;

export const OwnCooldownProjection = __t.object("OwnCooldownProjection", {
  id: __t.u64(),
  matchId: __t.u64(),
  identity: __t.identity(),
  power: __t.string(),
  readyAtMicros: __t.u64(),
});
export type OwnCooldownProjection = __Infer<typeof OwnCooldownProjection>;

export const OwnEmailContact = __t.object("OwnEmailContact", {
  identity: __t.identity(),
  email: __t.string(),
  source: __t.string(),
  verified: __t.bool(),
});
export type OwnEmailContact = __Infer<typeof OwnEmailContact>;

export const OwnIdentityLink = __t.object("OwnIdentityLink", {
  identity: __t.identity(),
  canonicalIdentity: __t.identity(),
});
export type OwnIdentityLink = __Infer<typeof OwnIdentityLink>;

export const OwnSpectatorCooldown = __t.object("OwnSpectatorCooldown", {});
export type OwnSpectatorCooldown = __Infer<typeof OwnSpectatorCooldown>;

export const PenDeskProjection = __t.object("PenDeskProjection", {
  matchId: __t.u64(),
  round: __t.u32(),
  humanRounds: __t.u32(),
  botRounds: __t.u32(),
  turn: __t.string(),
  humanX: __t.u32(),
  humanY: __t.u32(),
  botX: __t.u32(),
  botY: __t.u32(),
  turnsInRound: __t.u32(),
  lastOutcome: __t.string(),
});
export type PenDeskProjection = __Infer<typeof PenDeskProjection>;

export const PenDeskState = __t.object("PenDeskState", {});
export type PenDeskState = __Infer<typeof PenDeskState>;

export const PenFightMetrics = __t.object("PenFightMetrics", {
  id: __t.u64(),
  matchesStarted: __t.u64(),
  matchesCompleted: __t.u64(),
  uniquePlayers: __t.u64(),
  uniqueSpectators: __t.u64(),
  participants: __t.u64(),
  crowdActions: __t.u64(),
  roundsCompleted: __t.u64(),
  knockouts: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type PenFightMetrics = __Infer<typeof PenFightMetrics>;

export const PenFightMetricsIdentity = __t.object("PenFightMetricsIdentity", {
  identity: __t.identity(),
  hasPlayed: __t.u32(),
  hasSpectated: __t.u32(),
});
export type PenFightMetricsIdentity = __Infer<typeof PenFightMetricsIdentity>;

export const PenFightRecord = __t.object("PenFightRecord", {
  identity: __t.identity(),
  displayName: __t.string(),
  matchesPlayed: __t.u32(),
  wins: __t.u32(),
  roundsWon: __t.u32(),
  knockouts: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type PenFightRecord = __Infer<typeof PenFightRecord>;

export const PenFightState = __t.object("PenFightState", {
  matchId: __t.u64(),
  round: __t.u32(),
  humanRounds: __t.u32(),
  botRounds: __t.u32(),
  turn: __t.string(),
  humanX: __t.u32(),
  humanY: __t.u32(),
  botX: __t.u32(),
  botY: __t.u32(),
  turnsInRound: __t.u32(),
  lastOutcome: __t.string(),
  seed: __t.u64(),
});
export type PenFightState = __Infer<typeof PenFightState>;

export const PlayerProfile = __t.object("PlayerProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  melaLevel: __t.u32(),
  crowdInfluence: __t.u32(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const ProfileLinkChallenge = __t.object("ProfileLinkChallenge", {
  nonce: __t.string(),
  sourceIdentity: __t.identity(),
  expiresAtMicros: __t.u64(),
});
export type ProfileLinkChallenge = __Infer<typeof ProfileLinkChallenge>;

export const SpectatorCooldown = __t.object("SpectatorCooldown", {
  id: __t.u64(),
  matchId: __t.u64(),
  identity: __t.identity(),
  power: __t.string(),
  readyAtMicros: __t.u64(),
});
export type SpectatorCooldown = __Infer<typeof SpectatorCooldown>;

export const VisibleCrowdEffect = __t.object("VisibleCrowdEffect", {
  id: __t.u64(),
  matchId: __t.u64(),
  power: __t.string(),
  target: __t.string(),
  actorName: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type VisibleCrowdEffect = __Infer<typeof VisibleCrowdEffect>;

export const VisibleCrowdEffects = __t.object("VisibleCrowdEffects", {});
export type VisibleCrowdEffects = __Infer<typeof VisibleCrowdEffects>;

export const World = __t.object("World", {
  id: __t.u64(),
  name: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;

export const WorldActivity = __t.object("WorldActivity", {
  id: __t.u64(),
  worldId: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  occurredAt: __t.timestamp(),
});
export type WorldActivity = __Infer<typeof WorldActivity>;

export const WorldPresence = __t.object("WorldPresence", {
  identity: __t.identity(),
  worldId: __t.u64(),
  state: __t.string(),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type WorldPresence = __Infer<typeof WorldPresence>;

