// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BookCricketState = __t.object("BookCricketState", {
  matchId: __t.u64(),
  innings: __t.u32(),
  turn: __t.string(),
  humanScore: __t.u32(),
  botScore: __t.u32(),
  humanBalls: __t.u32(),
  botBalls: __t.u32(),
  humanWickets: __t.u32(),
  botWickets: __t.u32(),
  target: __t.u32(),
  lastOutcome: __t.string(),
  seed: __t.u64(),
});
export type BookCricketState = __Infer<typeof BookCricketState>;

export const ConnectionSession = __t.object("ConnectionSession", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type ConnectionSession = __Infer<typeof ConnectionSession>;

export const CrowdEffect = __t.object("CrowdEffect", {
  id: __t.u64(),
  matchId: __t.u64(),
  power: __t.string(),
  target: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type CrowdEffect = __Infer<typeof CrowdEffect>;

export const CrowdSchedule = __t.object("CrowdSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  kind: __t.string(),
  matchId: __t.u64(),
  effectId: __t.u64(),
});
export type CrowdSchedule = __Infer<typeof CrowdSchedule>;

export const LiveEvent = __t.object("LiveEvent", {
  id: __t.u64(),
  matchId: __t.u64(),
  message: __t.string(),
  occurredAt: __t.timestamp(),
});
export type LiveEvent = __Infer<typeof LiveEvent>;

export const Match = __t.object("Match", {
  id: __t.u64(),
  worldId: __t.u64(),
  gameKind: __t.string(),
  playerIdentity: __t.identity(),
  status: __t.string(),
  winner: __t.string(),
  createdAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
});
export type Match = __Infer<typeof Match>;

export const MatchCrowd = __t.object("MatchCrowd", {
  matchId: __t.u64(),
  energy: __t.u32(),
  maxEnergy: __t.u32(),
});
export type MatchCrowd = __Infer<typeof MatchCrowd>;

export const MatchHistory = __t.object("MatchHistory", {
  id: __t.u64(),
  matchId: __t.u64(),
  winner: __t.string(),
  humanScore: __t.u32(),
  botScore: __t.u32(),
  occurredAt: __t.timestamp(),
});
export type MatchHistory = __Infer<typeof MatchHistory>;

export const MatchParticipant = __t.object("MatchParticipant", {
  id: __t.u64(),
  matchId: __t.u64(),
  actorKind: __t.string(),
  role: __t.string(),
  identity: __t.option(__t.identity()),
  displayName: __t.string(),
});
export type MatchParticipant = __Infer<typeof MatchParticipant>;

export const MatchSpectator = __t.object("MatchSpectator", {
  id: __t.u64(),
  matchId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
});
export type MatchSpectator = __Infer<typeof MatchSpectator>;

export const PlayerProfile = __t.object("PlayerProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  melaLevel: __t.u32(),
  crowdInfluence: __t.u32(),
});
export type PlayerProfile = __Infer<typeof PlayerProfile>;

export const SpectatorCooldown = __t.object("SpectatorCooldown", {
  id: __t.u64(),
  matchId: __t.u64(),
  identity: __t.identity(),
  power: __t.string(),
  readyAtMicros: __t.u64(),
});
export type SpectatorCooldown = __Infer<typeof SpectatorCooldown>;

export const World = __t.object("World", {
  id: __t.u64(),
  name: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;

export const WorldActivity = __t.object("WorldActivity", {
  id: __t.u64(),
  worldId: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  occurredAt: __t.timestamp(),
});
export type WorldActivity = __Infer<typeof WorldActivity>;

export const WorldPresence = __t.object("WorldPresence", {
  identity: __t.identity(),
  worldId: __t.u64(),
  state: __t.string(),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type WorldPresence = __Infer<typeof WorldPresence>;
