// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as PlaygroundClockProcedure from "../playground_clock_procedure";

export type PlaygroundClockArgs = __Infer<
  typeof PlaygroundClockProcedure.params
>;
export type PlaygroundClockResult = __Infer<
  typeof PlaygroundClockProcedure.returnType
>;
