// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AgentFlickReducer from "../agent_flick_reducer";
import BeginProfileLinkReducer from "../begin_profile_link_reducer";
import ClaimAgentSeatReducer from "../claim_agent_seat_reducer";
import CompleteProfileLinkReducer from "../complete_profile_link_reducer";
import CreateAgentDuelReducer from "../create_agent_duel_reducer";
import CreateBookCricketReducer from "../create_book_cricket_reducer";
import CreateDotsBoxesReducer from "../create_dots_boxes_reducer";
import CreateGilliDandaReducer from "../create_gilli_danda_reducer";
import CreatePenFightReducer from "../create_pen_fight_reducer";
import DrawDotsEdgeReducer from "../draw_dots_edge_reducer";
import FlickPenReducer from "../flick_pen_reducer";
import JoinMatchAsSpectatorReducer from "../join_match_as_spectator_reducer";
import OnboardReducer from "../onboard_reducer";
import OnboardWithEmailReducer from "../onboard_with_email_reducer";
import PlayBallReducer from "../play_ball_reducer";
import StrikeGilliReducer from "../strike_gilli_reducer";
import UseCrowdPowerReducer from "../use_crowd_power_reducer";
import UsePenFightCrowdPowerReducer from "../use_pen_fight_crowd_power_reducer";

export type AgentFlickParams = __Infer<typeof AgentFlickReducer>;
export type BeginProfileLinkParams = __Infer<typeof BeginProfileLinkReducer>;
export type ClaimAgentSeatParams = __Infer<typeof ClaimAgentSeatReducer>;
export type CompleteProfileLinkParams = __Infer<typeof CompleteProfileLinkReducer>;
export type CreateAgentDuelParams = __Infer<typeof CreateAgentDuelReducer>;
export type CreateBookCricketParams = __Infer<typeof CreateBookCricketReducer>;
export type CreateDotsBoxesParams = __Infer<typeof CreateDotsBoxesReducer>;
export type CreateGilliDandaParams = __Infer<typeof CreateGilliDandaReducer>;
export type CreatePenFightParams = __Infer<typeof CreatePenFightReducer>;
export type DrawDotsEdgeParams = __Infer<typeof DrawDotsEdgeReducer>;
export type FlickPenParams = __Infer<typeof FlickPenReducer>;
export type JoinMatchAsSpectatorParams = __Infer<typeof JoinMatchAsSpectatorReducer>;
export type OnboardParams = __Infer<typeof OnboardReducer>;
export type OnboardWithEmailParams = __Infer<typeof OnboardWithEmailReducer>;
export type PlayBallParams = __Infer<typeof PlayBallReducer>;
export type StrikeGilliParams = __Infer<typeof StrikeGilliReducer>;
export type UseCrowdPowerParams = __Infer<typeof UseCrowdPowerReducer>;
export type UsePenFightCrowdPowerParams = __Infer<typeof UsePenFightCrowdPowerReducer>;

